openapi: 3.0.1
info:
  title: RTS FHIR API
  contact: {}
  version: "0.1"
servers:
  - url: https://rts-fhir.nihr.ac.uk/
    description: NIHR FHIR Server
tags:
  - name: Organization
    description: The Organization FHIR resource type
paths:
  /Organization/{id}:
    get:
      tags:
        - Organization
      summary: "read-instance: Read Organization instance"
      parameters:
        - name: id
          in: path
          description: An RTS Organization Identifier
          required: true
          style: simple
          schema:
            minimum: 1
            type: string
          example: f26b8ae9-183b-4cac-88e7-b5f508a58d0f
      responses:
        "200":
          description: Success
          content:
            application/fhir+json:
              examples:
                FHIR Organization:
                  value: |-
                    {
                      "resourceType": "Organization",
                      "id": "f26b8ae9-183b-4cac-88e7-b5f508a58d0f",
                      "meta": {
                        "lastUpdated": "2021-07-15T19:42:30.714+00:00"
                      },
                      "identifier": [
                        {
                          "value": "Q74@2.16.840.1.113883.2.1.3.8.2.7"
                        }
                      ],
                      "type": {
                        "coding": [{
                          "code": "GPPRACTICE@2.16.840.1.113883.5.110"
                        }],
                        "text": "GP PRACTICE"
                      },
                      "active": true,
                      "name": "FREEMAN HOSPITAL",
                      "address": [
                        {
                          "type": "postal",
                          "text": "FREEMAN HOSPITAL, FREEMAN ROAD, HIGH HEATON, NEWCASTLE UPON TYNE, TYNE AND WEAR, ENGLAND, NE7 7DN",
                          "line": ["FREEMAN HOSPITAL", "FREEMAN ROAD", "HIGH HEATON"],
                          "city": "NEWCASTLE UPON TYNE",
                          "postalCode": "NE7 7DN",
                          "district": "TYNE AND WEAR",
                          "country": "GB"
                        }
                      ],
                      "extension": [
                        {
                          "url": "https://rts-fhir.nihr.ac.uk/StructureDefinition/Extension-NIHR-Organization-Nullified",
                          "valueBoolean": false
                        },
                        {
                            "url": "https://rts-fhir.nihr.ac.uk/StructureDefinition/Extension-NIHR-Organization-StartDate",
                            "valueDateTime": "2011-10-05T14:48:00.000Z"
                        },
                        {
                            "url": "https://rts-fhir.nihr.ac.uk/StructureDefinition/Extension-NIHR-Organization-EndDate",
                            "valueDateTime": "2012-10-05T14:48:00.000Z"
                        },
                        {
                            "url": "https://rts-fhir.nihr.ac.uk/StructureDefinition/Extension-NIHR-Organization-Role",
                            "valueCodeableConcept": {
                                "coding": [{
                                    "code": "FUNDER@2.16.840.1.113883.2.1.3.8.5.1.4.1.1"
                                }],
                                "text": "CLINICAL RESEARCH SPONSOR",
                                "extension": [{
                                  "url": "startDate",
                                  "valueDateTime": "2011-10-05T14:48:00.000Z"
                                }, {
                                  "url": "endDate",
                                  "valueDateTime": "2011-10-05T14:48:00.000Z"
                                }, {
                                  "url": "status",
                                  "valueString": "Active"
                                }, {
                                  "url": "scoper",
                                  "valueReference": {
                                    "reference": "https://rts-fhir.nihr.ac.uk/Organization/f26b8ae9-183b-4cac-88e7-b5f508a58d0f",
                                    "type": "Organization",
                                    "display": "Test Organization"
                                  }
                                }]
                            }
                        }
                      ]
                    }

  /Organization:
    get:
      tags:
        - Organization
      summary: "search-type: Search for Organization instances"
      description: Search for Organization instances
      parameters:
        - name: identifier
          in: query
          description: >-
            Any identifier for the organization (not the accreditation issuer's
            identifier)
          schema:
            type: string
          example: K84016@2.16.840.1.113883.2.1.3.2.4.19.1
        - name: nihrType
          in: query
          description: Type of organisation (NIHR Organization Type Code)
          schema:
            type: string
          example: GPPRACTICE@2.16.840.1.113883.2.1.3.8.5.11.1.106
        - name: nihrRoleCode
          in: query
          description: Code for the organisation role
          schema:
            type: string
          example: RO279@2.16.840.1.113883.2.1.3.2.4.17.507
        - name: nihrRoleScoper
          in: query
          description: ID of the role's scoper
          schema:
            type: string
          example: SA999@2.16.840.1.113883.2.1.3.8.2.16.1
        - name: _lastUpdated
          in: query
          description: See https://www.hl7.org/fhir/search.html#lastUpdated
          schema:
            type: string
          example: gt2010-10-01
        - name: _count
          in: query
          description: See https://www.hl7.org/fhir/search.html#count
          schema:
            type: integer
          example: 100
      responses:
        "200":
          description: Success
          content:
            application/fhir+json:
              examples:
                FHIR Bundle containing Organizations:
                  value: |-
                    {
                      "resourceType": "Bundle",
                      "id": "166463ac-c1ff-45de-a0d2-b1110e74cc99",
                      "meta": {
                        "lastUpdated": "2021-11-23T18:04:43.860+00:00"
                      },
                      "type": "searchset",
                      "link": [
                        {
                          "relation": "self",
                          "url": "https://rts-fhir.nihr.ac.uk/Organization/f26b8ae9-183b-4cac-88e7-b5f508a58d0f"
                        },
                        {
                          "relation": "next",
                          "url": "https://rts-fhir.nihr.ac.uk/?_getpages=166463ac-c1ff-45de-a0d2-b1110e74cc99&_getpagesoffset=20&_count=20&_pretty=true&_bundletype=searchset"
                        }
                      ],
                      "entry": [
                        {
                          "fullUrl": "https://rts-fhir.nihr.ac.uk/Organization/f26b8ae9-183b-4cac-88e7-b5f508a58d0f",
                          "resource": {
                            "resourceType": "Organization",
                            "id": "f26b8ae9-183b-4cac-88e7-b5f508a58d0f",
                            "meta": {
                              "lastUpdated": "2021-07-15T19:42:30.714+00:00"
                            },
                            "identifier": [
                              {
                                "value": "Q74@2.16.840.1.113883.2.1.3.8.2.7"
                              }
                            ],
                            "type": {
                              "coding": [{
                                "code": "GPPRACTICE@2.16.840.1.113883.5.110"
                              }],
                              "text": "GP PRACTICE"
                            },
                            "active": true,
                            "name": "FREEMAN HOSPITAL",
                            "address": [
                              {
                                "type": "postal",
                                "text": "FREEMAN HOSPITAL, FREEMAN ROAD, HIGH HEATON, NEWCASTLE UPON TYNE, TYNE AND WEAR, ENGLAND, NE7 7DN",
                                "line": ["FREEMAN HOSPITAL", "FREEMAN ROAD", "HIGH HEATON"],
                                "city": "NEWCASTLE UPON TYNE",
                                "postalCode": "NE7 7DN",
                                "district": "TYNE AND WEAR",
                                "country": "GB"
                              }
                            ],
                            "extension": [
                              {
                                "url": "https://rts-fhir.nihr.ac.uk/StructureDefinition/Extension-NIHR-Organization-Nullified",
                                "valueBoolean": false
                              },
                              {
                                  "url": "https://rts-fhir.nihr.ac.uk/StructureDefinition/Extension-NIHR-Organization-StartDate",
                                  "valueDateTime": "2011-10-05T14:48:00.000Z"
                              },
                              {
                                  "url": "https://rts-fhir.nihr.ac.uk/StructureDefinition/Extension-NIHR-Organization-EndDate",
                                  "valueDateTime": "2012-10-05T14:48:00.000Z"
                              },
                              {
                                  "url": "https://rts-fhir.nihr.ac.uk/StructureDefinition/Extension-NIHR-Organization-Role",
                                  "valueCodeableConcept": {
                                      "coding": [{
                                          "code": "FUNDER@2.16.840.1.113883.2.1.3.8.5.1.4.1.1"
                                      }],
                                      "text": "FUNDER",
                                      "extension": [{
                                        "url": "startDate",
                                        "valueDateTime": "2011-10-05T14:48:00.000Z"
                                      }, {
                                        "url": "endDate",
                                        "valueDateTime": "2011-10-05T14:48:00.000Z"
                                      }, {
                                        "url": "status",
                                        "valueString": "Active"
                                      }, {
                                        "url": "scoper",
                                        "valueReference": {
                                          "reference": "https://rts-fhir.nihr.ac.uk/Organization/f26b8ae9-183b-4cac-88e7-b5f508a58d0f",
                                          "type": "Organization",
                                          "display": "Test Organization"
                                        }
                                      }]
                                  }
                              }
                            ]
                          },
                          "search": {
                            "mode": "match"
                          }
                        }
                      ]
                    }
